name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass rsync

    - name: Add known hosts
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Deploy to VPS
      env:
        SSHPASS: ${{ secrets.VPS_PASSWORD }}
        REMOTE_DIR: ${{ secrets.REMOTE_DIR || '/var/www/html/yankesdokpol' }}
        REMOTE_USER: ${{ secrets.REMOTE_USER || 'root' }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      run: |
        # Test connection
        sshpass -e ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "echo 'Connection successful'"
        
        # Create necessary directories
        sshpass -e ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST \
          "mkdir -p $REMOTE_DIR $REMOTE_DIR/uploads $REMOTE_DIR/dokumentasi"
        
        # Deploy using rsync
        sshpass -e rsync -avz --delete \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='.gitignore' \
          --exclude='.env' \
          --exclude='node_modules' \
          --exclude='vendor' \
          --exclude='sshkey*' \
          --exclude='assets/uploads' \
          --exclude='uploads' \
          --exclude='dokumentasi' \
          -e "sshpass -e ssh -o StrictHostKeyChecking=no" \
          ./ \
          $REMOTE_USER@$REMOTE_HOST:$REMOTE_DIR/

        # Set permissions
        sshpass -e ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
          chown -R www-data:www-data $REMOTE_DIR
          find $REMOTE_DIR -type d -not -path \"$REMOTE_DIR/uploads*\" -not -path \"$REMOTE_DIR/dokumentasi*\" -exec chmod 755 {} \;
          find $REMOTE_DIR -type f -not -path \"$REMOTE_DIR/uploads*\" -not -path \"$REMOTE_DIR/dokumentasi*\" -exec chmod 644 {} \;
          chmod -R 777 $REMOTE_DIR/uploads $REMOTE_DIR/dokumentasi 2>/dev/null
          echo 'Deployment completed successfully!'
        "