name: Deploy to Production

on:
  push:
    branches: [ main ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install lftp
      run: |
        sudo apt-get update
        sudo apt-get install -y lftp
        
    - name: Create deployment script
      run: |
        cat > deploy.lftp << 'EOL'
        set sftp:auto-confirm yes
        open sftp://${{ secrets.SFTP_USERNAME }}:${{ secrets.SFTP_PASSWORD }}@46.202.186.237:65002
        
        # Create main directory
        mkdir -p /domains/biddokkesjatim.org/public_html/yankesdokpol
        cd /domains/biddokkesjatim.org/public_html/yankesdokpol
        
        # Create necessary directories
        mkdir -p uploads
        mkdir -p dokumentasi
        mkdir -p assets
        mkdir -p api
        mkdir -p config
        mkdir -p content
        mkdir -p includes
        
        # Upload all files
        lcd $GITHUB_WORKSPACE
        
        # Upload root files
        mput -E *.php
        mput -E *.html
        mput -E *.json
        mput -E *.js
        mput -E .htaccess
        mput -E README.md
        
        # Upload directories
        mirror -R -v --parallel=5 --exclude .git/ --exclude .github/ --exclude .gitignore --exclude .env --exclude node_modules/ assets/ ./assets/
        mirror -R -v --parallel=5 --exclude .git/ --exclude .github/ --exclude .gitignore --exclude .env --exclude node_modules/ api/ ./api/
        mirror -R -v --parallel=5 --exclude .git/ --exclude .github/ --exclude .gitignore --exclude .env --exclude node_modules/ config/ ./config/
        mirror -R -v --parallel=5 --exclude .git/ --exclude .github/ --exclude .gitignore --exclude .env --exclude node_modules/ content/ ./content/
        mirror -R -v --parallel=5 --exclude .git/ --exclude .github/ --exclude .gitignore --exclude .env --exclude node_modules/ includes/ ./includes/
        
        # Set permissions
        chmod -R 755 .
        chmod -R 777 uploads
        chmod -R 777 dokumentasi
        
        bye
        EOL
        
        # Make script executable
        chmod +x deploy.lftp
        
    - name: Run deployment
      run: |
        lftp -f deploy.lftp
