name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Add known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H biddokkesjatim.org >> ~/.ssh/known_hosts
    
    - name: Deploy to server
      run: |
        # Buat direktori sementara
        mkdir -p ~/deploy_temp
        
        # Salin file ke direktori sementara
        rsync -avz --delete --exclude='.git' --exclude='.github' --exclude='.gitignore' \
              ./ u609399718@biddokkesjatim.org:/home/u609399718/domains/biddokkesjatim.org/public_html/yankesdokpol/
        
        # Set permission yang sesuai
        ssh u609399718@biddokkesjatim.org 'chmod -R 755 /home/u609399718/domains/biddokkesjatim.org/public_html/yankesdokpol/'
        ssh u609399718@biddokkesjatim.org 'chmod -R 777 /home/u609399718/domains/biddokkesjatim.org/public_html/yankesdokpol/uploads/'
        ssh u609399718@biddokkesjatim.org 'chmod -R 777 /home/u609399718/domains/biddokkesjatim.org/public_html/yankesdokpol/dokumentasi/'
