name: Deploy to Production

on:
  push:
    branches: [ main ]

env:
  SFTP_SERVER: 46.202.186.237
  SFTP_PORT: 65002
  SFTP_USERNAME: u609399718
  SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
  LOCAL_DIR: .
  REMOTE_DIR: /domains/biddokkesjatim.org/public_html/yankesdokpol

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install lftp
      run: |
        sudo apt-get update
        sudo apt-get install -y lftp
        
    - name: Create deployment script
      run: |
        cat > deploy.lftp << 'EOL'
        set sftp:auto-confirm yes
        open sftp://$SFTP_USERNAME:$SFTP_PASSWORD@$SFTP_SERVER:$SFTP_PORT
        
        # Create directories if they don't exist
        mkdir -p $REMOTE_DIR
        cd $REMOTE_DIR
        
        # Mirror local to remote
        mirror --reverse --delete --verbose \
          --exclude .git/ \
          --exclude .github/ \
          --exclude .gitignore \
          --exclude .env \
          --exclude node_modules/ \
          $LOCAL_DIR/ .
        
        # Set permissions
        chmod -R 755 .
        chmod -R 777 uploads/
        chmod -R 777 dokumentasi/
        
        bye
        EOL
        
        # Make script executable
        chmod +x deploy.lftp
        
    - name: Run deployment
      run: |
        lftp -f deploy.lftp
      env:
        SFTP_SERVER: ${{ env.SFTP_SERVER }}
        SFTP_PORT: ${{ env.SFTP_PORT }}
        SFTP_USERNAME: ${{ env.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ env.SFTP_PASSWORD }}
        LOCAL_DIR: ${{ env.LOCAL_DIR }}
        REMOTE_DIR: ${{ env.REMOTE_DIR }}
