name: Deploy ke Hostinger via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # Membuat folder deployment dan menyalin file yang diperlukan saja
      - name: Create deployment directory with rsync exclude
        run: |
          mkdir -p ./deploy_folder
          rsync -av --ignore-times --checksum --exclude='.git/' --exclude='node_modules/' --exclude='vendor/' --exclude='upload/' --exclude='uploads/' --exclude='.github/' --exclude='.DS_Store' --exclude='Thumbs.db' --exclude='.env' --exclude='.env.example' --exclude='.env.local' --exclude='README.md' --exclude='LICENSE' --exclude='composer.lock' --exclude='package-lock.json' --exclude='yarn.lock' --exclude='.vscode/' --exclude='.idea/' --exclude='logs/' --exclude='temp/' --exclude='tmp/' --exclude='cache/' --exclude='*.log' --exclude='*.bak' --exclude='*.swp' --exclude='*.sql' --exclude='*.zip' --exclude='*.tar' --exclude='*.gz' --exclude='*.rar' --exclude='sshkey' --exclude='*.psd' --exclude='*.ai' --exclude='*.sketch' ./ ./deploy_folder/

      # Debug: tampilkan isi folder deploy_folder
      - name: List files to be deployed
        run: |
          echo "Daftar file yang akan diupload:"
          find ./deploy_folder

      # Upload ke FTP
      - name: Deploy to Hostinger FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "./deploy_folder"
          remoteDir: "/public_html/yankesdokpol"
          options: "--delete --ascii --force"

# Jika terjadi error 530 Login incorrect:
# - Pastikan credential (FTP_HOST, FTP_USERNAME, FTP_PASSWORD) di GitHub Secrets sudah benar dan bisa login via FileZilla
# - Username/password FTP biasanya berbeda dengan login cPanel
# - Cek juga apakah user FTP punya akses ke folder tujuan
# - Jika tetap error, coba reset password FTP di panel hosting