name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install rsync
      run: |
        sudo apt-get update
        sudo apt-get install -y rsync

    - name: List files for debugging
      run: |
        echo "Current directory:"
        pwd
        ls -la
        echo "\nRoot directory files:"
        find . -maxdepth 1 -type f | sort
        echo "\nSubdirectories:"
        find . -maxdepth 1 -type d | sort

    - name: Deploy using rsync
      run: |
        echo "Starting deployment..."
        echo "Uploading files to server..."
        
        # Upload all files except those in .gitignore
        rsync -avz -e 'ssh -o StrictHostKeyChecking=no -p 65002' \
          --exclude '.git/' \
          --exclude '.github/' \
          --exclude '.gitignore' \
          --exclude '.env' \
          --exclude 'node_modules/' \
          --exclude 'vendor/' \
          --exclude 'sshkey*' \
          --delete \
          ./ \
          ${{ secrets.SFTP_USERNAME }}@46.202.186.237:/home/u609399718/domains/biddokkesjatim.org/public_html/yankesdokpol/
        
        echo "Setting permissions..."
        ssh -o StrictHostKeyChecking=no -p 65002 ${{ secrets.SFTP_USERNAME }}@46.202.186.237 \
          "cd /home/u609399718/domains/biddokkesjatim.org/public_html/yankesdokpol && \
           find . -type d -exec chmod 755 {} \; && \
           find . -type f -exec chmod 644 {} \; && \
           chmod -R 777 uploads dokumentasi"
        
        echo "Verifying deployment..."
        ssh -o StrictHostKeyChecking=no -p 65002 ${{ secrets.SFTP_USERNAME }}@46.202.186.237 \
          "ls -la /home/u609399718/domains/biddokkesjatim.org/public_html/yankesdokpol"
        
        echo "Deployment completed successfully!"
