name: Deploy to Production

on:
  push:
    branches: [ main ]

env:
  SFTP_SERVER: 46.202.186.237
  SFTP_PORT: 65002
  SFTP_USER: u609399718
  SFTP_PASS: ${{ secrets.SFTP_PASSWORD }}
  REMOTE_DIR: /home/u609399718/domains/biddokkesjatim.org/public_html/yankesdokpol

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install lftp
      run: |
        sudo apt-get update
        sudo apt-get install -y lftp

    - name: List files for debugging
      run: |
        echo "Current directory:"
        pwd
        ls -la
        echo "\nRoot directory files:"
        find . -maxdepth 1 -type f | sort
        echo "\nSubdirectories:"
        find . -maxdepth 1 -type d | sort

    - name: Deploy using LFTP
      run: |
        echo "Starting deployment..."
        
        # Create deployment script
        cat > deploy.lftp << 'EOL'
        set ssl:verify-certificate no
        set sftp:auto-confirm yes
        
        open sftp://${{ env.SFTP_USER }}:${{ env.SFTP_PASS }}@${{ env.SFTP_SERVER }}:${{ env.SFTP_PORT }}
        
        # Change to target directory
        cd ${{ env.REMOTE_DIR }}
        
        # Mirror local directory to remote
        mirror -v -R --delete --parallel=5 \
          --exclude .git/ \
          --exclude .github/ \
          --exclude .gitignore \
          --exclude .env \
          --exclude node_modules/ \
          --exclude vendor/ \
          --exclude sshkey* \
          /
        
        # Set permissions
        !find . -type d -exec chmod 755 {} \;
        !find . -type f -exec chmod 644 {} \;
        !chmod -R 777 uploads dokumentasi
        
        # List files after upload
        ls -la
        
        bye
        EOL
        
        # Execute the deployment
        lftp -f deploy.lftp
        
        echo "Deployment completed successfully!"
