name: Deploy ke Hostinger via FTP/SFTP

on:
  push:
    branches:
      - main

  workflow_dispatch:  # Menambahkan opsi trigger manual di GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Menambahkan timeout di tingkat job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Mengambil hanya 2 commit terakhir untuk mempercepat

      - name: Deploy via SFTP
        # Using SFTP-Deploy-Action which supports SFTP for shared hosting
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          # Use your shared hosting server address
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: ./
          remote_path: /public_html/yankesdokpol/
          # Connection timeout settings
          sftpArgs: '-o ConnectTimeout=30'
          # Exclude files and directories that shouldn't be deployed
          args: |
            --exclude='.git*'
            --exclude='.git*/**'
            --exclude='node_modules/**'
            --exclude='vendor/**'
            --exclude='upload/**'
            --exclude='uploads/**'
            --exclude='.DS_Store'
            --exclude='Thumbs.db'
            --exclude='.env'
            --exclude='.env.example'
            --exclude='.env.local'
            --exclude='README.md'
            --exclude='LICENSE'
            --exclude='composer.lock'
            --exclude='package-lock.json'
            --exclude='yarn.lock'
            --exclude='.vscode/**'
            --exclude='.idea/**'
            --exclude='logs/**'
            --exclude='temp/**'
            --exclude='tmp/**'
            --exclude='cache/**'
            --exclude='*.log'
            --exclude='*.bak'
            --exclude='*.swp'
            --exclude='*.sql'
            --exclude='*.zip'
            --exclude='*.tar'
            --exclude='*.gz'
            --exclude='*.rar'
            --exclude='sshkey'
            --exclude='*.psd'
            --exclude='*.ai'
            --exclude='*.sketch'