name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    # Allow manual trigger

env:
  SFTP_SERVER: 46.202.186.237
  SFTP_PORT: 65002
  SFTP_USER: u609399718
  SFTP_PASS: ${{ secrets.SFTP_PASSWORD }}
  REMOTE_DIR: /home/u609399718/domains/biddokkesjatim.org/public_html/yankesdokpol

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lftp sshpass

    - name: List files for debugging
      run: |
        echo "Current directory:"
        pwd
        ls -la
        echo "\nRoot directory files:"
        find . -maxdepth 1 -type f | sort
        echo "\nSubdirectories:"
        find . -maxdepth 1 -type d | sort

    - name: Test SFTP connection
      run: |
        echo "Testing SFTP connection..."
        sshpass -p "${{ secrets.SFTP_PASSWORD }}" sftp -o StrictHostKeyChecking=no -P ${{ env.SFTP_PORT }} ${{ env.SFTP_USER }}@${{ env.SFTP_SERVER }} <<EOF
        pwd
        ls -la
        exit
        EOF
        echo "SFTP connection test completed."

    - name: Deploy using LFTP
      run: |
        echo "Starting deployment..."
        
        # Create deployment script with timeouts
        cat > deploy.lftp << 'EOL'
        set ssl:verify-certificate no
        set sftp:auto-confirm yes
        set net:timeout 120
        set net:max-retries 3
        set net:reconnect-interval-base 5
        set net:reconnect-interval-multiplier 1
        
        open sftp://${{ env.SFTP_USER }}:${{ env.SFTP_PASS }}@${{ env.SFTP_SERVER }}:${{ env.SFTP_PORT }}
        
        # Change to target directory
        cd ${{ env.REMOTE_DIR }}
        
        # Create required directories if they don't exist
        !mkdir -p uploads dokumentasi
        
        # Mirror project directory to remote (only changed files)
        # Use smaller chunks with fewer parallel transfers
        mirror -v -R --only-newer --ignore-time --parallel=3 \
          --exclude .git/ \
          --exclude .github/ \
          --exclude .gitignore \
          --exclude .env \
          --exclude node_modules/ \
          --exclude vendor/ \
          --exclude sshkey* \
          --exclude assets/uploads/ \
          --exclude uploads/ \
          --exclude dokumentasi/ \
          .
        
        # Set directory permissions
        !find . -type d -not -path "./uploads*" -not -path "./dokumentasi*" -exec chmod 755 {} \;
        
        # Set file permissions
        !find . -type f -not -path "./uploads*" -not -path "./dokumentasi*" -exec chmod 644 {} \;
        
        # Special permissions for upload directories
        !chmod -R 777 uploads/ dokumentasi/ 2>/dev/null || true
        
        # List files after upload
        ls -la
        
        bye
        EOL
        
        # Execute the deployment with timeout
        timeout 600 lftp -f deploy.lftp
        
        echo "Deployment completed successfully!"
